//! Autogenerated weights for `pallet_private_channels`
//!
//! Placeholder values — re-run benchmarks after deploying to target hardware.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::weights::{Weight, constants::RocksDbWeight};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn create_channel() -> Weight;
    fn add_member() -> Weight;
    fn remove_member() -> Weight;
    fn update_member_role() -> Weight;
    fn post_data() -> Weight;
    fn share_data_cross_channel() -> Weight;
    fn close_channel() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn create_channel() -> Weight {
        Weight::from_parts(42_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn add_member() -> Weight {
        Weight::from_parts(32_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn remove_member() -> Weight {
        Weight::from_parts(28_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn update_member_role() -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn post_data() -> Weight {
        Weight::from_parts(36_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn share_data_cross_channel() -> Weight {
        Weight::from_parts(56_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(5))
    }
    fn close_channel() -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
}
