#!/usr/bin/env python3
"""
Quick Configuration Setup for Abena IHR Intelligence Layer
This script creates a basic .env file with the provided Slack webhook URL.
"""

import os
import getpass

def main():
    print("🔧 Quick Configuration Setup")
    print("=" * 40)
    
    # Get database password
    db_password = getpass.getpass("Database password: ")
    
    # Get API key
    api_key = getpass.getpass("API key (for authentication): ")
    
    # Configuration with your Slack webhook URL
    config = {
        "DATABASE_URL": f"postgresql://progres:{db_password}@localhost:5432/abena_ihr",
        "REDIS_URL": "redis://localhost:6379",
        "API_HOST": "0.0.0.0",
        "API_PORT": "8000",
        "PROMETHEUS_PORT": "8001",
        "SLACK_WEBHOOK_URL": "https://hooks.slack.com/services/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",
        "API_KEY_VALUE": api_key,
        "CORS_ORIGINS": "http://localhost:3000,http://localhost:8080",
        "LOG_LEVEL": "INFO",
        "LOG_FILE": "logs/intelligence_layer.log",
        "DEFAULT_ALERT_COOLDOWN_MINUTES": "15",
        "HIGH_ERROR_RATE_THRESHOLD": "0.05",
        "SLOW_RESPONSE_TIME_THRESHOLD": "30.0",
        "LOW_DATA_QUALITY_THRESHOLD": "0.7",
        "ANOMALY_DETECTION_CONTAMINATION": "0.1",
        "QUALITY_ANALYSIS_BATCH_SIZE": "1000",
        "HEALTH_CHECK_INTERVAL_SECONDS": "60",
        "FAILURE_DETECTION_INTERVAL_SECONDS": "300",
        "SYSTEM_HEALTH_THRESHOLD": "50",
        "MAX_CONCURRENT_REQUESTS": "100",
        "REQUEST_TIMEOUT_SECONDS": "30",
        "CACHE_TTL_SECONDS": "3600",
        "DB_POOL_SIZE": "10",
        "DB_MAX_OVERFLOW": "20",
        "DB_POOL_TIMEOUT": "30",
        "REDIS_MAX_CONNECTIONS": "20",
        "REDIS_SOCKET_TIMEOUT": "5",
        "REDIS_SOCKET_CONNECT_TIMEOUT": "5"
    }
    
    # Write to .env file
    with open(".env", 'w') as f:
        f.write("# Abena IHR Intelligence Layer Environment Configuration\n")
        f.write("# Generated by quick_setup.py\n\n")
        
        for key, value in config.items():
            f.write(f"{key}={value}\n")
    
    print("✅ Configuration written to .env file")
    print("\n📚 Next steps:")
    print("   1. Review the generated .env file")
    print("   2. Start the services: ./start.sh")
    print("   3. Test the API: curl http://localhost:8000/health")
    print("   4. Access the dashboard: http://localhost:8000/dashboard")

if __name__ == "__main__":
    main() 