//! Autogenerated weights for `pallet_permissioned_validators`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! Run with: `./target/release/abena-node benchmark pallet --pallet pallet_permissioned_validators`
//!
//! Placeholder values — re-run benchmarks after deploying to target hardware.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::weights::{Weight, constants::RocksDbWeight};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn set_network_mode() -> Weight;
    fn propose_new_validator() -> Weight;
    fn add_validator() -> Weight;
    fn remove_validator() -> Weight;
    fn update_validator() -> Weight;
    fn register_institution() -> Weight;
    fn approve_institution() -> Weight;
    fn revoke_institution() -> Weight;
}

/// Weights using the Substrate reference hardware benchmark baseline.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn set_network_mode() -> Weight {
        Weight::from_parts(12_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn propose_new_validator() -> Weight {
        // Similar to add_validator + governance propose overhead.
        Weight::from_parts(48_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(3))
    }

    fn add_validator() -> Weight {
        Weight::from_parts(32_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    fn remove_validator() -> Weight {
        Weight::from_parts(28_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    fn update_validator() -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn register_institution() -> Weight {
        Weight::from_parts(32_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    fn approve_institution() -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn revoke_institution() -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
}
