apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: abena-ihr
  labels:
    app: auth
    version: v1
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: metrics
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: auth
    version: v1
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800 