"""
Core Data Models for Abena IHR System

This module contains the data structures used throughout the system
for representing patients, treatments, outcomes, and clinical data.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional
from datetime import datetime
from enum import Enum


class TreatmentType(Enum):
    """Treatment type enumeration"""
    PHARMACOLOGICAL = "pharmacological"
    BEHAVIORAL = "behavioral"
    COMBINED = "combined"
    LIFESTYLE = "lifestyle"


class RiskLevel(Enum):
    """Risk level enumeration"""
    MINIMAL = "MINIMAL"
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


@dataclass
class PatientProfile:
    """Comprehensive patient profile for clinical analysis"""
    patient_id: str
    age: int
    gender: str
    genomics_data: Dict[str, float]
    biomarkers: Dict[str, float]
    medical_history: List[str]
    current_medications: List[str]
    lifestyle_metrics: Dict[str, float]
    pain_scores: List[float]
    functional_assessments: Dict[str, float]
    allergies: List[str] = field(default_factory=list)
    lab_results: Dict[str, float] = field(default_factory=dict)
    vital_signs: Dict[str, float] = field(default_factory=dict)
    comorbidities: List[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.now)
    
    def __post_init__(self):
        """Validate patient data after initialization"""
        if self.age < 0 or self.age > 120:
            raise ValueError(f"Invalid age: {self.age}")
        
        if self.gender not in ['male', 'female', 'other']:
            # Allow flexibility but normalize
            self.gender = self.gender.lower()
        
        # Ensure pain scores are within valid range
        self.pain_scores = [max(0, min(10, score)) for score in self.pain_scores]


@dataclass
class TreatmentPlan:
    """Treatment plan with medications and interventions"""
    treatment_id: str
    treatment_type: str
    medications: List[str]
    dosages: Dict[str, str]
    duration_weeks: int
    lifestyle_interventions: List[str]
    contraindications: List[str] = field(default_factory=list)
    side_effects: List[str] = field(default_factory=list)
    cost_estimate: float = 0.0
    evidence_level: str = "Level III"
    monitoring_requirements: List[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.now)
    
    def __post_init__(self):
        """Validate treatment plan after initialization"""
        if self.duration_weeks <= 0:
            raise ValueError(f"Invalid duration: {self.duration_weeks}")
        
        if self.treatment_type not in ['pharmacological', 'behavioral', 'combined', 'lifestyle']:
            self.treatment_type = 'combined'  # Default fallback


@dataclass
class PredictionResult:
    """Result of treatment response prediction"""
    patient_id: str
    treatment_id: str
    success_probability: float
    risk_score: float
    key_factors: List[str]
    warnings: List[str]
    timestamp: datetime
    confidence_interval: tuple = (0.0, 1.0)
    feature_importance: Dict[str, float] = field(default_factory=dict)
    model_version: str = "1.0.0"
    
    def __post_init__(self):
        """Validate prediction result"""
        if not (0 <= self.success_probability <= 1):
            raise ValueError(f"Invalid success probability: {self.success_probability}")
        
        if not (0 <= self.risk_score <= 1):
            raise ValueError(f"Invalid risk score: {self.risk_score}")


@dataclass
class AdverseEventPrediction:
    """Prediction of adverse events"""
    patient_id: str
    treatment_id: str
    overall_risk_level: str
    risk_scores: Dict[str, Dict[str, Any]]
    recommendations: List[str]
    timestamp: datetime = field(default_factory=datetime.now)
    
    def __post_init__(self):
        """Validate adverse event prediction"""
        valid_risk_levels = ['MINIMAL', 'LOW', 'MODERATE', 'HIGH', 'CRITICAL']
        if self.overall_risk_level not in valid_risk_levels:
            self.overall_risk_level = 'MODERATE'  # Default fallback


@dataclass
class ClinicalNote:
    """Clinical note generated by the system"""
    note_id: str
    patient_id: str
    provider_id: str
    note_type: str
    title: str
    content: str
    created_at: datetime = field(default_factory=datetime.now)
    signed: bool = False
    
    def sign_note(self, provider_id: str):
        """Sign the clinical note"""
        if self.provider_id == provider_id:
            self.signed = True
        else:
            raise ValueError("Only the creating provider can sign the note")


@dataclass
class Alert:
    """Clinical alert for providers"""
    alert_id: str
    patient_id: str
    provider_id: str
    alert_type: str
    priority: str
    title: str
    message: str
    recommendations: List[str]
    created_at: datetime
    expires_at: Optional[datetime]
    acknowledged: bool = False
    acknowledged_at: Optional[datetime] = None
    acknowledged_by: Optional[str] = None
    
    def acknowledge(self, provider_id: str):
        """Acknowledge the alert"""
        self.acknowledged = True
        self.acknowledged_at = datetime.now()
        self.acknowledged_by = provider_id


@dataclass
class TreatmentOutcome:
    """Treatment outcome data for feedback"""
    patient_id: str
    treatment_id: str
    outcome_success: bool
    recovery_time: int  # days
    side_effects_observed: List[str]
    patient_satisfaction: float  # 1-10 scale
    readmission_required: bool
    outcome_date: datetime
    pain_improvement: Optional[float] = None
    functional_improvement: Optional[float] = None
    quality_of_life_score: Optional[float] = None
    
    def __post_init__(self):
        """Validate treatment outcome"""
        if not (1 <= self.patient_satisfaction <= 10):
            raise ValueError(f"Invalid satisfaction score: {self.patient_satisfaction}")
        
        if self.recovery_time < 0:
            raise ValueError(f"Invalid recovery time: {self.recovery_time}")


@dataclass
class ModelMetrics:
    """ML model performance metrics"""
    model_name: str
    accuracy: float
    precision: float
    recall: float
    f1_score: float
    auc_roc: float
    timestamp: datetime = field(default_factory=datetime.now)
    
    def __post_init__(self):
        """Validate metrics"""
        metrics = [self.accuracy, self.precision, self.recall, self.f1_score, self.auc_roc]
        for metric in metrics:
            if not (0 <= metric <= 1):
                raise ValueError(f"Invalid metric value: {metric}")


@dataclass
class ValidationMetrics:
    """Model validation metrics for deployment decisions"""
    accuracy: float
    precision: float
    recall: float
    f1_score: float
    improvement: float
    validation_loss: float
    cross_validation_score: float = 0.0
    
    def __post_init__(self):
        """Validate metrics"""
        if not (0 <= self.accuracy <= 1):
            raise ValueError(f"Invalid accuracy: {self.accuracy}")
        
        if not (0 <= self.precision <= 1):
            raise ValueError(f"Invalid precision: {self.precision}")
        
        if not (0 <= self.recall <= 1):
            raise ValueError(f"Invalid recall: {self.recall}")


@dataclass
class EMRData:
    """EMR integration data structure"""
    patient_id: str
    patient: Dict[str, Any]
    observations: List[Dict[str, Any]]
    medications: List[Dict[str, Any]]
    conditions: List[Dict[str, Any]]
    retrieved_at: datetime = field(default_factory=datetime.now)
    source_system: str = "unknown"
    
    def get_latest_vitals(self) -> Dict[str, float]:
        """Extract latest vital signs from observations"""
        vitals = {}
        for obs in self.observations:
            if obs.get('category') == 'vital-signs':
                vitals[obs.get('code', 'unknown')] = obs.get('value', 0.0)
        return vitals


# Compatibility aliases for existing code
PatientData = PatientProfile  # Alias for backward compatibility
FinalRecommendation = TreatmentPlan  # Temporary alias


# Utility functions for data validation
def validate_patient_data(patient: PatientProfile) -> bool:
    """Validate patient data completeness and correctness"""
    try:
        # Check required fields
        required_fields = ['patient_id', 'age', 'gender']
        for field in required_fields:
            if not getattr(patient, field):
                return False
        
        # Check data types and ranges
        if not isinstance(patient.age, int) or patient.age < 0:
            return False
        
        if patient.gender not in ['male', 'female', 'other']:
            return False
        
        # Check for valid pain scores
        if patient.pain_scores:
            for score in patient.pain_scores:
                if not (0 <= score <= 10):
                    return False
        
        return True
    
    except Exception:
        return False


def validate_treatment_plan(treatment: TreatmentPlan) -> bool:
    """Validate treatment plan completeness and correctness"""
    try:
        # Check required fields
        if not treatment.treatment_id or not treatment.treatment_type:
            return False
        
        # Check duration
        if not isinstance(treatment.duration_weeks, int) or treatment.duration_weeks <= 0:
            return False
        
        # Check treatment type
        valid_types = ['pharmacological', 'behavioral', 'combined', 'lifestyle']
        if treatment.treatment_type not in valid_types:
            return False
        
        return True
    
    except Exception:
        return False


def create_sample_patient(patient_id: str = "SAMPLE_PATIENT") -> PatientProfile:
    """Create a sample patient for testing purposes"""
    return PatientProfile(
        patient_id=patient_id,
        age=45,
        gender="female",
        genomics_data={
            'CYP2C9_activity': 0.7,
            'OPRM1_variant': 1,
            'COMT_activity': 1.2,
            'CB1_receptor_density': 0.9
        },
        biomarkers={
            'inflammatory_markers': 1.8,
            'endocannabinoid_levels': 0.6,
            'cortisol_baseline': 15.2,
            'gaba_activity': 0.8
        },
        medical_history=['chronic_pain', 'anxiety'],
        current_medications=['gabapentin'],
        lifestyle_metrics={
            'sleep_quality': 6.0,
            'stress_level': 7.0
        },
        pain_scores=[8.0, 7.5, 8.2, 7.8],
        functional_assessments={'mobility_score': 35.0}
    )


def create_sample_treatment(treatment_id: str = "SAMPLE_TREATMENT") -> TreatmentPlan:
    """Create a sample treatment plan for testing purposes"""
    return TreatmentPlan(
        treatment_id=treatment_id,
        treatment_type="combined",
        medications=['pregabalin', 'cbd_oil'],
        dosages={'pregabalin': '150mg_bid', 'cbd_oil': '25mg_daily'},
        duration_weeks=12,
        lifestyle_interventions=['mindfulness', 'physical_therapy']
    )